/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package programas;

import classes.ConexaoAzure;
import classes.AzureUser;
import com.github.britooo.looca.api.core.Looca;
import java.awt.Desktop;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import javax.swing.ImageIcon;
import org.springframework.jdbc.core.BeanPropertyRowMapper;
import java.util.List;
import javax.swing.JOptionPane;
import java.io.IOException;
import org.json.JSONObject;

public class TelaLogin extends javax.swing.JFrame {

    ConexaoAzure conectar = new ConexaoAzure();
    Looca comp = new Looca();

    public TelaLogin() {

        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        PFsenha = new javax.swing.JPasswordField();
        JTFemail = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        BTLogar = new javax.swing.JButton();
        LbIcon = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(null);
        jPanel1.add(PFsenha);
        PFsenha.setBounds(270, 250, 290, 30);
        jPanel1.add(JTFemail);
        JTFemail.setBounds(270, 180, 290, 30);

        jLabel1.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Senha");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(190, 250, 70, 30);

        jLabel3.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Email");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(190, 180, 70, 30);

        jLabel4.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(252, 197, 119));
        jLabel4.setText("Ir para Site");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel4);
        jLabel4.setBounds(340, 300, 140, 20);

        BTLogar.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        BTLogar.setText("Entrar");
        BTLogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTLogarActionPerformed(evt);
            }
        });
        jPanel1.add(BTLogar);
        BTLogar.setBounds(320, 400, 180, 30);

        LbIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Original.png"))); // NOI18N
        jPanel1.add(LbIcon);
        LbIcon.setBounds(320, 30, 144, 60);

        jPanel2.setBackground(new java.awt.Color(252, 197, 119));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 760, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(10, 110, 760, 1);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 780, 490);

        setSize(new java.awt.Dimension(794, 526));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BTLogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTLogarActionPerformed
        String email = JTFemail.getText();
        String senha = PFsenha.getText();

        List<AzureUser> consultaCadastro = ConexaoAzure.jdbcTemplate.query(
                "Select * from tbUsuario where emailUsuario = ? and senha = ?",
                new BeanPropertyRowMapper(AzureUser.class),
                email, senha);

        if (!consultaCadastro.isEmpty()) {
            for (AzureUser users : consultaCadastro) {
                JOptionPane.showMessageDialog(null, "Login efetuado com sucesso. Bem vindo(a) "
                        + users.getNomeUsuario());

                try {
                    enviarMensagemLoginSlack(users.getNomeUsuario());
                } catch (IOException | InterruptedException e) {
                    System.out.println(e);
                }

                new TelaDash().setVisible(true);
                dispose();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Email ou senha incorreto!");
        }
    }//GEN-LAST:event_BTLogarActionPerformed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        try {
            URI link = new URI("www.google.com");
            Desktop.getDesktop().browse(link);
        } catch (IOException | URISyntaxException e) {
            System.out.println("Error!");
        }
    }//GEN-LAST:event_jLabel4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });

    }

    public void enviarMensagemLoginSlack(String nome) throws IOException, InterruptedException {
        JSONObject json = new JSONObject();

        json.put("text", String.format("O usuário %s logou agora no software Zini!!!", nome));
        Slack.enviarMensagem(json);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTLogar;
    private javax.swing.JTextField JTFemail;
    private javax.swing.JLabel LbIcon;
    private javax.swing.JPasswordField PFsenha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
